import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import { Providers } from "./providers";
import { DeviceDetectProvider } from "@/components/device-detect/server";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen !bg-background font-sans antialiased`}
      >
        <div vaul-drawer-wrapper="">
          <DeviceDetectProvider>
            <Providers>{children}</Providers>
          </DeviceDetectProvider>
        </div>
        <TailwindIndicator />
        <Toaster />
      </body>
    </html>
  );
}
